### ISSUE TITLE
Support for non-numeric data points for visualisation in Grafana

### ISSUE THREAD

**Issue by chaurasiavishal** [rockset/rockset-grafana-backend#38]
I have a Rockset data source added to my Grafana server. While performing the query, the query was only able to return the numeric data. We contacted Rockset support regarding the same and found out that the Rockset plugin for Grafana currently doesn't support the non-numeric fields for visualizations.

We are raising this feature request to implement this feature in rockset plugin for grafana, thus it will be easy to visualize, the dashboards in the form of table will be great.

**Comment by pmenglund** [comment]
this was addressed in the v0.3.0 release

**Comment by chaurasiavishal** [comment]
Hello @pmenglund I installed the v0.3.0 cli, and checked the access the non-numeric data, but I was unable to get the non-numeric data. It returned error as "no usable column found".

Here I have attached the artifacts for same.


![image](https://github.com/rockset/rockset-grafana-backend/assets/133360224/d2519069-56e2-4c48-90e9-b66c19dc0f3d)


![image](https://github.com/rockset/rockset-grafana-backend/assets/133360224/0280e56d-6dcb-47e5-81a2-88c7d9ac30f0)
